_robot_type = Type("robot", ["x", "y", "z", "tilt", "wrist", "fingers", "bbox_left", "bbox_right", "bbox_upper", "bbox_lower"])
_jug_type = Type("jug", ["x", "y", "bbox_left", "bbox_right", "bbox_upper", "bbox_lower"])
_cup_type = Type("cup", ["x", "y", "bbox_left", "bbox_right", "bbox_upper", "bbox_lower"])
_machine_type = Type("machine", ["bbox_left", "bbox_right", "bbox_upper", "bbox_lower"])
_table_type = Type("table", [])