# PG4 experiments.
---
APPROACHES:
  pg3:
    NAME: "pg3"
    FLAGS:
      pg3_hc_enforced_depth: 1
  pg4:
    NAME: "pg4"
    FLAGS:
      pg3_hc_enforced_depth: 1
  plan-only:
    NAME: "oracle"
    FLAGS: []
ENVS:
  cover-easy:  # downward refinable. PG3 should succeed
    NAME: "cover"
    FLAGS:
      cover_initial_holding_prob: 0.0
  cover:  # PG3 should sometimes fail, but PG4 should succeed
    NAME: "cover"
    FLAGS: []
ARGS: []
FLAGS:
  strips_learner: oracle
  sampler_learner: oracle
  num_train_tasks: 50
START_SEED: 456
NUM_SEEDS: 10
