# A configuration file for evaluation on 5 pick and place BEHAVIOR tasks.
# python scripts/supercloud/launch.py \
# --user wmcclinton \
# --config behavior_pick_place_evaluation.yaml \
# --transfer_local_data \
# --supercloud_dir ~/GitHub/predicators_behavior
---
APPROACHES:
  oracle: # Oracle
    NAME: "oracle"
  pnad_search: # PNAD search approach.
    NAME: "nsrt_learning"
    FLAGS:
      strips_learner: pnad_search
  cluster_and_intersect:  # Cluster-and-intersect baseline.
    NAME: "nsrt_learning"
    FLAGS:
      strips_learner: "cluster_and_intersect"
      disable_harmlessness_check: True
  cluster_and_search:  # LOFT baseline.
    NAME: "nsrt_learning"
    FLAGS:
      strips_learner: "cluster_and_search"
      disable_harmlessness_check: True
  pred_error:  # Prediction error baseline that optimizes via hill climbing.
    NAME: "nsrt_learning"
    FLAGS: 
      strips_learner: "cluster_and_intersect_sideline_prederror" 
      disable_harmlessness_check: True
  gnn_shooting:  # Model-based GNN option policy baseline.
    NAME: "gnn_option_policy"
  # gnn_modelfree:  # Model-free GNN option policy baseline. Note: this needs to run after Model-based GNN
  #   NAME: "gnn_option_policy"
  #   FLAGS:
  #     gnn_option_policy_solve_with_shooting: False
ENVS:
  collecting-aluminum-cans-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Ihlen_1_int
      behavior_test_scene_name: Pomaria_2_int
      behavior_task_list: "[collecting_aluminum_cans]"
      behavior_option_model_eval: True
      horizon: 50
  opening-presents-Pomaria_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_2_int
      behavior_test_scene_name: Benevolence_2_int
      behavior_task_list: "[opening_presents]"
      behavior_option_model_eval: True
      horizon: 50
  locking-every-window-Merom_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Merom_1_int
      behavior_test_scene_name: Wainscott_0_int
      behavior_task_list: "[locking_every_window]"
      behavior_option_model_eval: True
      horizon: 50
  sorting-books-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_1_int
      behavior_test_scene_name: Ihlen_0_int
      behavior_task_list: "[sorting_books]"
      behavior_option_model_eval: True
      horizon: 50
ARGS:
  - "load_data"
  - "load_atoms"
FLAGS:  # general flags
  offline_data_planning_timeout: 500.0
  timeout: 500.0
  plan_only_eval: True
  sesame_task_planner: fdsat
  behavior_override_learned_samplers: True
  num_train_tasks: 10
  num_test_tasks: 10
START_SEED: 456
NUM_SEEDS: 10
USE_GPU: True
