# An example configuration file.
---
APPROACHES:
  backchaining:
    NAME: "nsrt_learning"
    FLAGS:
      offline_data_planning_timeout: 500.0
      timeout: 500.0
      sampler_learner: neural
      strips_learner: backchaining
      plan_only_eval: True
      sesame_task_planner: fdopt
ENVS:
  opening-packages-Pomaria_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_2_int
      behavior_task_list: "[opening_packages]"
      behavior_option_model_eval: True
  opening-presents-Pomaria_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Pomaria_2_int
      behavior_task_list: "[opening_presents]"
      behavior_option_model_eval: True
  locking_every_door-Merom_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Merom_1_int
      behavior_task_list: "[locking_every_door]"
      behavior_option_model_eval: True
  locking_every_window-Merom_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_scene_name: Merom_1_int
      behavior_task_list: "[locking_every_window]"
      behavior_option_model_eval: True
ARGS: {}
FLAGS:  # general flags
  num_train_tasks: 10
  num_test_tasks: 10
START_SEED: 456
NUM_SEEDS: 3
USE_GPU: True
