# A configuration file for evaluation on 4 pick and place BEHAVIOR tasks.
# Note that not all baselines can be run at once. Comment things out, change flags,
# and run accordingly.
# Example Usage:
# python scripts/supercloud/launch.py \
# --user wmcclinton \
# --config behavior_pick_place_evaluation.yaml \
# --transfer_local_data \
# --supercloud_dir ~/GitHub/predicators_behavior
---
APPROACHES:
  oracle: # Oracle
    NAME: "oracle"
  pnad_search: # PNAD search approach.
    NAME: "nsrt_learning"
    FLAGS:
      strips_learner: pnad_search
  cluster_and_intersect:  # Cluster-and-intersect baseline.
    NAME: "nsrt_learning"
    FLAGS:
      strips_learner: "cluster_and_intersect"
      disable_harmlessness_check: True
  cluster_and_search:  # LOFT baseline.
    NAME: "nsrt_learning"
    FLAGS:
      strips_learner: "cluster_and_search"
      disable_harmlessness_check: True
  pred_error:  # Prediction error baseline that optimizes via hill climbing.
    NAME: "nsrt_learning"
    FLAGS: 
      strips_learner: "cluster_and_intersect_sideline_prederror" 
      disable_harmlessness_check: True
  # NOTE: Set the 'plan_only_eval' flag to false when running either
  # of the below GNN approaches.
  # gnn_shooting:  # Model-based GNN option policy baseline.
  #   NAME: "gnn_option_policy"
  # Model-free GNN option policy baseline.
  #   NAME: "gnn_option_policy"
  #   FLAGS:
  #     gnn_option_policy_solve_with_shooting: False
ENVS:
  collecting-aluminum-cans-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Ihlen_1_int
      behavior_test_scene_name: Pomaria_2_int
      behavior_task_list: "[collecting_aluminum_cans]"
      behavior_option_model_eval: True
      horizon: 1000
  opening-presents-Pomaria_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_2_int
      behavior_test_scene_name: Benevolence_2_int
      behavior_task_list: "[opening_presents]"
      behavior_option_model_eval: True
      horizon: 1000
  locking-every-window-Merom_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Merom_1_int
      behavior_test_scene_name: Wainscott_0_int
      behavior_task_list: "[locking_every_window]"
      behavior_option_model_eval: True
      horizon: 1000
  sorting-books-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_1_int
      behavior_test_scene_name: Ihlen_0_int
      behavior_task_list: "[sorting_books]"
      behavior_option_model_eval: True
      horizon: 1000
ARGS:
  - "load_data"
  - "load_atoms"
FLAGS:  # general flags
  # NOTE: set below timeouts to 2000.0 for sorting-book.
  offline_data_planning_timeout: 500 #2000.0
  timeout: 500 #2000.0
  # NOTE: set below to False when using GNN's!
  plan_only_eval: True #False
  sesame_task_planner: fdsat
  behavior_override_learned_samplers: True
  behavior_ignore_discover_failures: True
  num_train_tasks: 10
  num_test_tasks: 0
START_SEED: 463
NUM_SEEDS: 2
USE_GPU: True
