# Comparing oracle bridge policy approach to oracle bilevel planning
# in the painting environment.
---
APPROACHES:
  bilevel-planning:
    NAME: "oracle"
    FLAGS:
      painting_raise_environment_failure: False
  bilevel-planning-with-feedback:
    NAME: "oracle"
    FLAGS:
      painting_raise_environment_failure: True
  oracle-bridge:
    NAME: "bridge_policy"
    FLAGS:
      bridge_policy: "oracle"
      painting_raise_environment_failure: False
ENVS:
  painting-2:
    NAME: "painting"
    FLAGS:
      painting_num_objs_test: "[2]"
ARGS:
  - "debug"
FLAGS:  # general flags
  num_train_tasks: 0
  num_test_tasks: 50
START_SEED: 456
NUM_SEEDS: 1
