# Comparing oracle bridge policy approach to oracle bilevel planning
# in the stick button environment.
# NOTE: button_radius in stick button environment manually changed to 0.01.
---
APPROACHES:
  # oracle-bridge:
  #   NAME: "bridge_policy"
  #   FLAGS:
  #     bridge_policy: "oracle"
  #     painting_raise_environment_failure: False
  oracle-bridge-fd:
    NAME: "bridge_policy"
    FLAGS:
      bridge_policy: "oracle"
      painting_raise_environment_failure: False
      sesame_task_planner: "fdsat"
  # bilevel-planning:
  #   NAME: "oracle"
ENVS:
  # stick_button-2:
  #   NAME: "stick_button"
  #   FLAGS:
  #     stick_button_num_buttons_test: "[2]"
  # stick_button-5:
  #   NAME: "stick_button"
  #   FLAGS:
  #     stick_button_num_buttons_test: "[5]"
  # stick_button-10:
  #   NAME: "stick_button"
  #   FLAGS:
  #     stick_button_num_buttons_test: "[10]"
  stick_button-25:
    NAME: "stick_button"
    FLAGS:
      stick_button_num_buttons_test: "[25]"
ARGS:
  - "debug"
FLAGS:  # general flags
  button_radius: 
  num_train_tasks: 0
  num_test_tasks: 10
  horizon: 100000
START_SEED: 456
NUM_SEEDS: 1
