# An example configuration file showing how to define multiple approach/env
# combinations, i.e., not just one cross product. In this example, the oracle
# approach is run in cover, and both the oracle approach and nsrt_learning are
# run in blocks.
---
APPROACHES:
  oracle:
    NAME: "oracle"
ENVS:
  cover:
    NAME: "cover"
ARGS: []
FLAGS: {}
START_SEED: 456
NUM_SEEDS: 3
...
---
APPROACHES:
  oracle:
    NAME: "oracle"
  nsrt-learning:
    NAME: "nsrt_learning"
ENVS:
  blocks:
    NAME: "blocks"
ARGS: []
FLAGS: {}
START_SEED: 456
NUM_SEEDS: 3
