# Sanity test for online RL approach.
---
APPROACHES:
  maple_q:
    NAME: "maple_q"
    FLAGS:
      explorer: "maple_q"
      mlp_regressor_max_itr: 640000
      active_sampler_learning_batch_size: 512
ENVS:
  discrete_regional_bumpy_cover:
    NAME: "regional_bumpy_cover"
    FLAGS:
      regional_bumpy_cover_include_impossible_nsrt: "True"  # NOTE
      bumpy_cover_init_bumpy_prob: 0.0  # NOTE
      bumpy_cover_num_bumps: 3
      bumpy_cover_spaces_per_bump: 3
      cover_num_blocks: 1
      cover_block_widths: '[0.01]'
      cover_num_targets: 1
      cover_target_widths: '[0.008]'
  continuous_regional_bumpy_cover:
    NAME: "regional_bumpy_cover"
    FLAGS:
      regional_bumpy_cover_include_impossible_nsrt: "False"  # NOTE
      bumpy_cover_init_bumpy_prob: 1.0  # NOTE
      bumpy_cover_num_bumps: 3
      bumpy_cover_spaces_per_bump: 3
      cover_num_blocks: 1
      cover_block_widths: '[0.01]'
      cover_num_targets: 1
      cover_target_widths: '[0.008]'
  hybrid_regional_bumpy_cover:
    NAME: "regional_bumpy_cover"
    FLAGS:
      regional_bumpy_cover_include_impossible_nsrt: "True"  # NOTE
      bumpy_cover_init_bumpy_prob: 1.0  # NOTE
      bumpy_cover_num_bumps: 3
      bumpy_cover_spaces_per_bump: 3
      cover_num_blocks: 1
      cover_block_widths: '[0.01]'
      cover_num_targets: 1
      cover_target_widths: '[0.008]'
ARGS:
  - "debug"
FLAGS:
  strips_learner: "oracle"
  sampler_learner: "oracle"
  bilevel_plan_without_sim: "True"
  max_initial_demos: 0
  online_nsrt_learning_requests_per_cycle: 200
  num_online_learning_cycles: 20
  num_train_tasks: 1000
  num_test_tasks: 10
  max_num_steps_interaction_request: 5
  horizon: 2  # NOTE, otherwise too easy
START_SEED: 456
NUM_SEEDS: 5
