# Active sampler learning experiment on Spot.
---
APPROACHES:
  main:
    NAME: "spot_wrapper[active_sampler_learning]"
    FLAGS:
      explorer: "active_sampler"
      active_sampler_explore_task_strategy: "planning_progress"
ENVS:
  spot_ball_and_cup_sticky_table_env:
    NAME: "spot_ball_and_cup_sticky_table_env"
    FLAGS:
      spot_robot_ip: "10.17.30.21"  # Donner
      perceiver: "spot_perceiver"
      execution_monitor: "expected_atoms"
      spot_graph_nav_map: "floor8-cup-table"
      spot_render_perception_outputs: False
      active_sampler_learning_object_specific_samplers: True
ARGS:
  - "debug"
FLAGS:
  strips_learner: "oracle"
  sampler_learner: "oracle"
  segmenter: "spot"
  bilevel_plan_without_sim: "True"
  max_initial_demos: 0
  num_train_tasks: 1000  # doesn't really matter
  num_test_tasks: 0  # can add back later if we want
  sampler_mlp_classifier_max_itr: 100000
  mlp_classifier_balance_data: False
  pytorch_train_print_every: 10000
  active_sampler_learning_n_iter_no_change: 5000
  active_sampler_learning_model: "myopic_classifier_mlp"
  active_sampler_learning_use_teacher: False
  active_sampler_learning_explore_length_base: 10000
  active_sampler_learning_exploration_epsilon: 0.5
  active_sampler_learning_explore_pursue_goal_interval: 3
  active_sampler_learning_init_cycles_to_pursue_goal: 5
  skill_competence_model_optimistic_recency_size: 5
  skill_competence_model_optimistic_window_size: 5
  horizon: 15
  active_sampler_learning_feature_selection: oracle
  online_nsrt_learning_requests_per_cycle: 1
  max_num_steps_interaction_request: 20
  num_online_learning_cycles: 100
  sesame_task_planner: "fdopt-costs"
  sesame_grounder: "fd_translator"
START_SEED: 123
NUM_SEEDS: 1
