repos:
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    -   id: docformatter
        args: [--in-place]
-   repo: git@github.com:pre-commit/mirrors-yapf.git
    rev: v0.26.0
    hooks:
    - id: yapf
      args: ['--style=.style.yapf', '--parallel', '--in-place']